"""initial

Revision ID: 998057b95511
Revises: 
Create Date: 2018-12-06 15:12:20.574082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998057b95511'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
